version: "2"
output:
  sort-order:
    - linter
    - severity
    - file
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dupl
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forcetypeassert
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - iface
    - ineffassign
    - makezero
    - misspell
    - mnd
    - modernize
    - musttag
    - nakedret
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    #- nolintlint
    - prealloc
    - predeclared
    - recvcheck
    - revive
    - sloglint
    - staticcheck
    - testifylint
    - thelper
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - wastedassign
  disable:
    - unused
  settings:
    gocognit:
      min-complexity: 15
    gocritic:
      disabled-checks:
        - commentFormatting
        - commentedOutCode
      enabled-tags:
        - style
        - diagnostic
        - performance
    revive:
      rules:
        - name: unused-parameter
          disabled: true
    gosec:
      # Configure gosec for security scanning
      excludes:
        - G104  # Audit errors not checked (covered by errcheck)
      severity: medium
      confidence: medium
    prealloc:
      # Configure prealloc for slice optimization
      simple: true
      range-loops: true
      for-loops: true
    exhaustive:
      # Check exhaustiveness of enum switch statements
      default-signifies-exhaustive: true
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true
  new: false
